# For Python 3.7 support we need to explicitly set the distribution
# See: https://docs.travis-ci.com/user/languages/python/
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # Does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
# command to run tests
script: nosetests
